import React, { useState } from 'react';
import Layout from '../components/layout/Layout';
import SettingsSection from '../components/settings/SettingsSection';
import {
  Settings,
  Bell,
  Camera,
  Thermometer,
  Mail,
  Users,
  Shield,
  Database,
  Clock,
  Save,
  RefreshCw,
  Download,
  Upload,
  Eye,
  EyeOff,
  Globe,
  Moon,
  Sun,
  Volume2,
  Vibrate
} from 'lucide-react';

const SettingsPage = () => {
  const [settings, setSettings] = useState({
    // Paramètres généraux
    language: 'fr',
    theme: 'light',
    timezone: 'Africa/Casablanca',
    dateFormat: 'dd/MM/yyyy',
    timeFormat: '24h',
    
    // Notifications
    emailNotifications: true,
    smsNotifications: false,
    pushNotifications: true,
    alertSound: true,
    vibration: true,
    criticalAlertsOnly: false,
    
    // Alertes températures
    tempWarningThreshold: 60,
    tempCriticalThreshold: 75,
    tempCheckInterval: 5,
    autoAcknowledgeAfter: 24,
    
    // Caméras
    cameraRefreshRate: 30,
    defaultGridSize: '3x3',
    showCameraNames: true,
    showTemperature: true,
    thermalColorScheme: 'rainbow',
    
    // Rapports
    reportEmail: 'supervision@marsamaroc.ma',
    autoGenerateDaily: true,
    autoGenerateWeekly: true,
    autoGenerateMonthly: false,
    reportTime: '08:00',
    
    // Sécurité
    sessionTimeout: 30,
    twoFactorAuth: false,
    loginAttempts: 5,
    ipWhitelist: '',
    
    // Stockage
    retentionDays: 30,
    autoBackup: true,
    backupTime: '02:00',
    maxStorage: 100
  });

  const [isEditing, setIsEditing] = useState(false);
  const [showPassword, setShowPassword] = useState(false);

  const handleSave = () => {
    setIsEditing(false);
    alert('Paramètres sauvegardés avec succès !');
  };

  const handleReset = () => {
    if (window.confirm('Réinitialiser tous les paramètres ?')) {
      window.location.reload();
    }
  };

  const handleExport = () => {
    const dataStr = JSON.stringify(settings, null, 2);
    const dataUri = 'data:application/json;charset=utf-8,' + encodeURIComponent(dataStr);
    const exportFileDefaultName = `settings_backup_${new Date().toISOString().split('T')[0]}.json`;
    const linkElement = document.createElement('a');
    linkElement.setAttribute('href', dataUri);
    linkElement.setAttribute('download', exportFileDefaultName);
    linkElement.click();
  };

  const handleImport = (e) => {
    const file = e.target.files[0];
    if (file) {
      const reader = new FileReader();
      reader.onload = (e) => {
        try {
          const imported = JSON.parse(e.target.result);
          setSettings(imported);
          alert('Paramètres importés avec succès !');
        } catch (error) {
          alert('Erreur lors de l\'importation');
        }
      };
      reader.readAsText(file);
    }
  };

  const updateSetting = (key, value) => {
    setSettings(prev => ({ ...prev, [key]: value }));
  };

  return (
    <Layout title="Paramètres">
      <div className="space-y-6">
        {/* En-tête */}
        <div className="flex justify-between items-center">
          <div className="flex items-center space-x-2">
            <Settings size={24} className="text-[#003A6B]" />
            <h2 className="text-xl font-bold text-gray-800">Configuration</h2>
          </div>
          <div className="flex items-center space-x-2">
            <button
              onClick={() => document.getElementById('import-file').click()}
              className="flex items-center space-x-2 px-4 py-2 border border-gray-200 rounded-lg hover:bg-gray-50"
            >
              <Upload size={16} />
              <span>Importer</span>
            </button>
            <input
              id="import-file"
              type="file"
              accept=".json"
              onChange={handleImport}
              className="hidden"
            />
            <button
              onClick={handleExport}
              className="flex items-center space-x-2 px-4 py-2 border border-gray-200 rounded-lg hover:bg-gray-50"
            >
              <Download size={16} />
              <span>Exporter</span>
            </button>
            <button
              onClick={handleReset}
              className="flex items-center space-x-2 px-4 py-2 border border-gray-200 rounded-lg hover:bg-gray-50"
            >
              <RefreshCw size={16} />
              <span>Réinitialiser</span>
            </button>
            {!isEditing ? (
              <button
                onClick={() => setIsEditing(true)}
                className="px-4 py-2 bg-[#003A6B] text-white rounded-lg hover:bg-[#002B4F]"
              >
                Modifier
              </button>
            ) : (
              <button
                onClick={handleSave}
                className="flex items-center space-x-2 px-4 py-2 bg-green-600 text-white rounded-lg hover:bg-green-700"
              >
                <Save size={16} />
                <span>Sauvegarder</span>
              </button>
            )}
          </div>
        </div>

        {/* Grille des paramètres */}
        <div className="space-y-4">
          {/* Paramètres généraux */}
          <SettingsSection title="Général" icon={Globe} defaultOpen={true}>
            <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
              <div>
                <label className="block text-sm font-medium text-gray-700 mb-2">
                  Langue
                </label>
                <select
                  value={settings.language}
                  onChange={(e) => updateSetting('language', e.target.value)}
                  disabled={!isEditing}
                  className="w-full px-4 py-2 border border-gray-200 rounded-lg focus:outline-none focus:ring-2 focus:ring-[#003A6B] disabled:bg-gray-100"
                >
                  <option value="fr">Français</option>
                  <option value="en">English</option>
                  <option value="ar">العربية</option>
                </select>
              </div>

              <div>
                <label className="block text-sm font-medium text-gray-700 mb-2">
                  Thème
                </label>
                <div className="flex space-x-4">
                  <label className="flex items-center space-x-2">
                    <input
                      type="radio"
                      value="light"
                      checked={settings.theme === 'light'}
                      onChange={(e) => updateSetting('theme', e.target.value)}
                      disabled={!isEditing}
                      className="w-4 h-4 text-[#003A6B]"
                    />
                    <Sun size={16} className="text-gray-600" />
                    <span className="text-sm">Clair</span>
                  </label>
                  <label className="flex items-center space-x-2">
                    <input
                      type="radio"
                      value="dark"
                      checked={settings.theme === 'dark'}
                      onChange={(e) => updateSetting('theme', e.target.value)}
                      disabled={!isEditing}
                      className="w-4 h-4 text-[#003A6B]"
                    />
                    <Moon size={16} className="text-gray-600" />
                    <span className="text-sm">Sombre</span>
                  </label>
                </div>
              </div>

              <div>
                <label className="block text-sm font-medium text-gray-700 mb-2">
                  Fuseau horaire
                </label>
                <select
                  value={settings.timezone}
                  onChange={(e) => updateSetting('timezone', e.target.value)}
                  disabled={!isEditing}
                  className="w-full px-4 py-2 border border-gray-200 rounded-lg focus:outline-none focus:ring-2 focus:ring-[#003A6B] disabled:bg-gray-100"
                >
                  <option value="Africa/Casablanca">Casablanca (GMT+1)</option>
                  <option value="UTC">UTC</option>
                  <option value="Europe/Paris">Paris (GMT+2)</option>
                </select>
              </div>

              <div>
                <label className="block text-sm font-medium text-gray-700 mb-2">
                  Format date
                </label>
                <select
                  value={settings.dateFormat}
                  onChange={(e) => updateSetting('dateFormat', e.target.value)}
                  disabled={!isEditing}
                  className="w-full px-4 py-2 border border-gray-200 rounded-lg focus:outline-none focus:ring-2 focus:ring-[#003A6B] disabled:bg-gray-100"
                >
                  <option value="dd/MM/yyyy">31/12/2026</option>
                  <option value="MM/dd/yyyy">12/31/2026</option>
                  <option value="yyyy-MM-dd">2026-12-31</option>
                </select>
              </div>
            </div>
          </SettingsSection>

          {/* Notifications */}
          <SettingsSection title="Notifications" icon={Bell}>
            <div className="space-y-4">
              <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                <label className="flex items-center justify-between p-3 bg-white rounded-lg border border-gray-200">
                  <span className="text-sm font-medium">Notifications email</span>
                  <input
                    type="checkbox"
                    checked={settings.emailNotifications}
                    onChange={(e) => updateSetting('emailNotifications', e.target.checked)}
                    disabled={!isEditing}
                    className="w-5 h-5 text-[#003A6B] rounded"
                  />
                </label>

                <label className="flex items-center justify-between p-3 bg-white rounded-lg border border-gray-200">
                  <span className="text-sm font-medium">Notifications SMS</span>
                  <input
                    type="checkbox"
                    checked={settings.smsNotifications}
                    onChange={(e) => updateSetting('smsNotifications', e.target.checked)}
                    disabled={!isEditing}
                    className="w-5 h-5 text-[#003A6B] rounded"
                  />
                </label>

                <label className="flex items-center justify-between p-3 bg-white rounded-lg border border-gray-200">
                  <span className="text-sm font-medium">Notifications push</span>
                  <input
                    type="checkbox"
                    checked={settings.pushNotifications}
                    onChange={(e) => updateSetting('pushNotifications', e.target.checked)}
                    disabled={!isEditing}
                    className="w-5 h-5 text-[#003A6B] rounded"
                  />
                </label>

                <label className="flex items-center justify-between p-3 bg-white rounded-lg border border-gray-200">
                  <span className="text-sm font-medium">Son d'alerte</span>
                  <input
                    type="checkbox"
                    checked={settings.alertSound}
                    onChange={(e) => updateSetting('alertSound', e.target.checked)}
                    disabled={!isEditing}
                    className="w-5 h-5 text-[#003A6B] rounded"
                  />
                </label>

                <label className="flex items-center justify-between p-3 bg-white rounded-lg border border-gray-200">
                  <span className="text-sm font-medium">Vibration</span>
                  <input
                    type="checkbox"
                    checked={settings.vibration}
                    onChange={(e) => updateSetting('vibration', e.target.checked)}
                    disabled={!isEditing}
                    className="w-5 h-5 text-[#003A6B] rounded"
                  />
                </label>

                <label className="flex items-center justify-between p-3 bg-white rounded-lg border border-gray-200">
                  <span className="text-sm font-medium">Alertes critiques seulement</span>
                  <input
                    type="checkbox"
                    checked={settings.criticalAlertsOnly}
                    onChange={(e) => updateSetting('criticalAlertsOnly', e.target.checked)}
                    disabled={!isEditing}
                    className="w-5 h-5 text-[#003A6B] rounded"
                  />
                </label>
              </div>

              <div>
                <label className="block text-sm font-medium text-gray-700 mb-2">
                  Email pour notifications
                </label>
                <input
                  type="email"
                  value={settings.reportEmail}
                  onChange={(e) => updateSetting('reportEmail', e.target.value)}
                  disabled={!isEditing}
                  className="w-full px-4 py-2 border border-gray-200 rounded-lg focus:outline-none focus:ring-2 focus:ring-[#003A6B] disabled:bg-gray-100"
                  placeholder="supervision@marsamaroc.ma"
                />
              </div>
            </div>
          </SettingsSection>

          {/* Alertes température */}
          <SettingsSection title="Alertes température" icon={Thermometer}>
            <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
              <div>
                <label className="block text-sm font-medium text-gray-700 mb-2">
                  Seuil d'avertissement (°C)
                </label>
                <input
                  type="number"
                  value={settings.tempWarningThreshold}
                  onChange={(e) => updateSetting('tempWarningThreshold', parseInt(e.target.value))}
                  disabled={!isEditing}
                  className="w-full px-4 py-2 border border-gray-200 rounded-lg focus:outline-none focus:ring-2 focus:ring-[#003A6B] disabled:bg-gray-100"
                  min="0"
                  max="100"
                />
              </div>

              <div>
                <label className="block text-sm font-medium text-gray-700 mb-2">
                  Seuil critique (°C)
                </label>
                <input
                  type="number"
                  value={settings.tempCriticalThreshold}
                  onChange={(e) => updateSetting('tempCriticalThreshold', parseInt(e.target.value))}
                  disabled={!isEditing}
                  className="w-full px-4 py-2 border border-gray-200 rounded-lg focus:outline-none focus:ring-2 focus:ring-[#003A6B] disabled:bg-gray-100"
                  min="0"
                  max="100"
                />
              </div>

              <div>
                <label className="block text-sm font-medium text-gray-700 mb-2">
                  Intervalle vérification (minutes)
                </label>
                <input
                  type="number"
                  value={settings.tempCheckInterval}
                  onChange={(e) => updateSetting('tempCheckInterval', parseInt(e.target.value))}
                  disabled={!isEditing}
                  className="w-full px-4 py-2 border border-gray-200 rounded-lg focus:outline-none focus:ring-2 focus:ring-[#003A6B] disabled:bg-gray-100"
                  min="1"
                  max="60"
                />
              </div>

              <div>
                <label className="block text-sm font-medium text-gray-700 mb-2">
                  Auto-acceptation après (heures)
                </label>
                <input
                  type="number"
                  value={settings.autoAcknowledgeAfter}
                  onChange={(e) => updateSetting('autoAcknowledgeAfter', parseInt(e.target.value))}
                  disabled={!isEditing}
                  className="w-full px-4 py-2 border border-gray-200 rounded-lg focus:outline-none focus:ring-2 focus:ring-[#003A6B] disabled:bg-gray-100"
                  min="1"
                  max="168"
                />
              </div>
            </div>
          </SettingsSection>

          {/* Caméras */}
          <SettingsSection title="Caméras" icon={Camera}>
            <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
              <div>
                <label className="block text-sm font-medium text-gray-700 mb-2">
                  Rafraîchissement (secondes)
                </label>
                <input
                  type="number"
                  value={settings.cameraRefreshRate}
                  onChange={(e) => updateSetting('cameraRefreshRate', parseInt(e.target.value))}
                  disabled={!isEditing}
                  className="w-full px-4 py-2 border border-gray-200 rounded-lg focus:outline-none focus:ring-2 focus:ring-[#003A6B] disabled:bg-gray-100"
                  min="5"
                  max="300"
                />
              </div>

              <div>
                <label className="block text-sm font-medium text-gray-700 mb-2">
                  Grille par défaut
                </label>
                <select
                  value={settings.defaultGridSize}
                  onChange={(e) => updateSetting('defaultGridSize', e.target.value)}
                  disabled={!isEditing}
                  className="w-full px-4 py-2 border border-gray-200 rounded-lg focus:outline-none focus:ring-2 focus:ring-[#003A6B] disabled:bg-gray-100"
                >
                  <option value="2x2">2x2</option>
                  <option value="3x3">3x3</option>
                  <option value="4x4">4x4</option>
                </select>
              </div>

              <label className="flex items-center justify-between p-3 bg-white rounded-lg border border-gray-200">
                <span className="text-sm font-medium">Afficher noms caméras</span>
                <input
                  type="checkbox"
                  checked={settings.showCameraNames}
                  onChange={(e) => updateSetting('showCameraNames', e.target.checked)}
                  disabled={!isEditing}
                  className="w-5 h-5 text-[#003A6B] rounded"
                />
              </label>

              <label className="flex items-center justify-between p-3 bg-white rounded-lg border border-gray-200">
                <span className="text-sm font-medium">Afficher température</span>
                <input
                  type="checkbox"
                  checked={settings.showTemperature}
                  onChange={(e) => updateSetting('showTemperature', e.target.checked)}
                  disabled={!isEditing}
                  className="w-5 h-5 text-[#003A6B] rounded"
                />
              </label>
            </div>
          </SettingsSection>

          {/* Rapports automatiques */}
          <SettingsSection title="Rapports automatiques" icon={Mail}>
            <div className="space-y-4">
              <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                <label className="flex items-center justify-between p-3 bg-white rounded-lg border border-gray-200">
                  <span className="text-sm font-medium">Rapport quotidien</span>
                  <input
                    type="checkbox"
                    checked={settings.autoGenerateDaily}
                    onChange={(e) => updateSetting('autoGenerateDaily', e.target.checked)}
                    disabled={!isEditing}
                    className="w-5 h-5 text-[#003A6B] rounded"
                  />
                </label>

                <label className="flex items-center justify-between p-3 bg-white rounded-lg border border-gray-200">
                  <span className="text-sm font-medium">Rapport hebdomadaire</span>
                  <input
                    type="checkbox"
                    checked={settings.autoGenerateWeekly}
                    onChange={(e) => updateSetting('autoGenerateWeekly', e.target.checked)}
                    disabled={!isEditing}
                    className="w-5 h-5 text-[#003A6B] rounded"
                  />
                </label>

                <label className="flex items-center justify-between p-3 bg-white rounded-lg border border-gray-200">
                  <span className="text-sm font-medium">Rapport mensuel</span>
                  <input
                    type="checkbox"
                    checked={settings.autoGenerateMonthly}
                    onChange={(e) => updateSetting('autoGenerateMonthly', e.target.checked)}
                    disabled={!isEditing}
                    className="w-5 h-5 text-[#003A6B] rounded"
                  />
                </label>
              </div>

              <div>
                <label className="block text-sm font-medium text-gray-700 mb-2">
                  Heure d'envoi
                </label>
                <input
                  type="time"
                  value={settings.reportTime}
                  onChange={(e) => updateSetting('reportTime', e.target.value)}
                  disabled={!isEditing}
                  className="w-full px-4 py-2 border border-gray-200 rounded-lg focus:outline-none focus:ring-2 focus:ring-[#003A6B] disabled:bg-gray-100"
                />
              </div>
            </div>
          </SettingsSection>

          {/* Sécurité */}
          <SettingsSection title="Sécurité" icon={Shield}>
            <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
              <div>
                <label className="block text-sm font-medium text-gray-700 mb-2">
                  Timeout session (minutes)
                </label>
                <input
                  type="number"
                  value={settings.sessionTimeout}
                  onChange={(e) => updateSetting('sessionTimeout', parseInt(e.target.value))}
                  disabled={!isEditing}
                  className="w-full px-4 py-2 border border-gray-200 rounded-lg focus:outline-none focus:ring-2 focus:ring-[#003A6B] disabled:bg-gray-100"
                  min="5"
                  max="120"
                />
              </div>

              <div>
                <label className="block text-sm font-medium text-gray-700 mb-2">
                  Tentatives de connexion max
                </label>
                <input
                  type="number"
                  value={settings.loginAttempts}
                  onChange={(e) => updateSetting('loginAttempts', parseInt(e.target.value))}
                  disabled={!isEditing}
                  className="w-full px-4 py-2 border border-gray-200 rounded-lg focus:outline-none focus:ring-2 focus:ring-[#003A6B] disabled:bg-gray-100"
                  min="3"
                  max="10"
                />
              </div>

              <label className="flex items-center justify-between p-3 bg-white rounded-lg border border-gray-200">
                <span className="text-sm font-medium">Double authentification</span>
                <input
                  type="checkbox"
                  checked={settings.twoFactorAuth}
                  onChange={(e) => updateSetting('twoFactorAuth', e.target.checked)}
                  disabled={!isEditing}
                  className="w-5 h-5 text-[#003A6B] rounded"
                />
              </label>
            </div>
          </SettingsSection>

          {/* Stockage */}
          <SettingsSection title="Stockage" icon={Database}>
            <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
              <div>
                <label className="block text-sm font-medium text-gray-700 mb-2">
                  Rétention données (jours)
                </label>
                <input
                  type="number"
                  value={settings.retentionDays}
                  onChange={(e) => updateSetting('retentionDays', parseInt(e.target.value))}
                  disabled={!isEditing}
                  className="w-full px-4 py-2 border border-gray-200 rounded-lg focus:outline-none focus:ring-2 focus:ring-[#003A6B] disabled:bg-gray-100"
                  min="7"
                  max="365"
                />
              </div>

              <div>
                <label className="block text-sm font-medium text-gray-700 mb-2">
                  Stockage max (GB)
                </label>
                <input
                  type="number"
                  value={settings.maxStorage}
                  onChange={(e) => updateSetting('maxStorage', parseInt(e.target.value))}
                  disabled={!isEditing}
                  className="w-full px-4 py-2 border border-gray-200 rounded-lg focus:outline-none focus:ring-2 focus:ring-[#003A6B] disabled:bg-gray-100"
                  min="10"
                  max="10000"
                />
              </div>

              <label className="flex items-center justify-between p-3 bg-white rounded-lg border border-gray-200">
                <span className="text-sm font-medium">Sauvegarde automatique</span>
                <input
                  type="checkbox"
                  checked={settings.autoBackup}
                  onChange={(e) => updateSetting('autoBackup', e.target.checked)}
                  disabled={!isEditing}
                  className="w-5 h-5 text-[#003A6B] rounded"
                />
              </label>

              {settings.autoBackup && (
                <div>
                  <label className="block text-sm font-medium text-gray-700 mb-2">
                    Heure sauvegarde
                  </label>
                  <input
                    type="time"
                    value={settings.backupTime}
                    onChange={(e) => updateSetting('backupTime', e.target.value)}
                    disabled={!isEditing}
                    className="w-full px-4 py-2 border border-gray-200 rounded-lg focus:outline-none focus:ring-2 focus:ring-[#003A6B] disabled:bg-gray-100"
                  />
                </div>
              )}
            </div>
          </SettingsSection>
        </div>

        {/* Barre d'actions en bas */}
        {isEditing && (
          <div className="sticky bottom-4 bg-white border border-gray-200 rounded-lg shadow-lg p-4 flex justify-end space-x-3">
            <button
              onClick={() => setIsEditing(false)}
              className="px-4 py-2 border border-gray-200 rounded-lg hover:bg-gray-50"
            >
              Annuler
            </button>
            <button
              onClick={handleSave}
              className="px-4 py-2 bg-[#003A6B] text-white rounded-lg hover:bg-[#002B4F] flex items-center"
            >
              <Save size={16} className="mr-2" />
              Sauvegarder les modifications
            </button>
          </div>
        )}
      </div>
    </Layout>
  );
};

export default SettingsPage;
